### ISSUE TITLE
Wrong license classifier in setup.py

### ISSUE THREAD

**Issue by frankIT** [kedder/ofxstatement-sample#4]
When trying to twine upload to testPyPi a plugin made from this bolerplate, i recived:

> HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'License :: OSI Approved :: GNU General Public License v3' is not a valid choice for this field for url: https://test.pypi.org/legacy/

the classifier should be:
> 'License :: OSI Approved :: GNU General Public License v3 (GPLv3)'

as it is in the ofxstatement repo

**Comment by kedder** [comment]
Closing afte rmerge of #5, thank you!
