### ISSUE TITLE
pipenv config outdated?

### ISSUE THREAD

**Issue by maxcco** [kedder/ofxstatement-sample#9]
Hello,

When I try to do pipenv sync --dev with the sample project, i get 
`An error occurred while installing attrs==20.3.0 --hash=sha256:832aa3cde19744e49938b91fea06d69ecb9e649c93ba974535d08ad92164f700 --hash=sha256:31b2eced602aa8423c2aea9c76a724617ed67cf9513173fd3a4f03e3a929c7e6! Will try again.`
and the same for all the rest of the package 

tested on ubuntu 23.04

**Comment by kedder** [comment]
I have upgraded dependencies in #10, can you pull master and try again?
